FROM oven/bun:latest

WORKDIR /app

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock ./

RUN bun install --production

COPY . .

RUN bunx prisma generate

# Generate data on build
# RUN python3 data/scripts/generate_data.py

CMD ["bun", "run", "start"]