    # Use an official Node.js runtime as a parent image
FROM oven/bun:latest

# Set the working directory in the container
WORKDIR /app

# Copy package*.json files
COPY package*.json ./

# Install dependencies
RUN bun install

# Copy the rest of the application code
COPY . .

# Expose the port the app will run on
EXPOSE 4000

# Run the command to start the app when the container launches
CMD ["bun", "run", "init:api"]
